# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Source Code/oled_constraints.xdc

# Block Designs: bd/zynq_interrupt_system/zynq_interrupt_system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_interrupt_system || ORIG_REF_NAME==zynq_interrupt_system}]

# IP: bd/zynq_interrupt_system/ip/zynq_interrupt_system_processing_system7_0_0/zynq_interrupt_system_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_interrupt_system_processing_system7_0_0 || ORIG_REF_NAME==zynq_interrupt_system_processing_system7_0_0}]

# IP: bd/zynq_interrupt_system/ip/zynq_interrupt_system_axi_gpio_0_0/zynq_interrupt_system_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_interrupt_system_axi_gpio_0_0 || ORIG_REF_NAME==zynq_interrupt_system_axi_gpio_0_0}]

# IP: bd/zynq_interrupt_system/ip/zynq_interrupt_system_processing_system7_0_axi_periph_0/zynq_interrupt_system_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_interrupt_system_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==zynq_interrupt_system_processing_system7_0_axi_periph_0}]

# IP: bd/zynq_interrupt_system/ip/zynq_interrupt_system_rst_processing_system7_0_50M_0/zynq_interrupt_system_rst_processing_system7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_interrupt_system_rst_processing_system7_0_50M_0 || ORIG_REF_NAME==zynq_interrupt_system_rst_processing_system7_0_50M_0}]

# IP: bd/zynq_interrupt_system/ip/zynq_interrupt_system_ZedboardOLED_0_0/zynq_interrupt_system_ZedboardOLED_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_interrupt_system_ZedboardOLED_0_0 || ORIG_REF_NAME==zynq_interrupt_system_ZedboardOLED_0_0}]

# IP: bd/zynq_interrupt_system/ip/zynq_interrupt_system_ZedboardOLED_0_0/src/charLib/charLib.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==charLib || ORIG_REF_NAME==charLib}]

# IP: bd/zynq_interrupt_system/ip/zynq_interrupt_system_xbar_0/zynq_interrupt_system_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_interrupt_system_xbar_0 || ORIG_REF_NAME==zynq_interrupt_system_xbar_0}]

# IP: bd/zynq_interrupt_system/ip/zynq_interrupt_system_axi_timer_0_0/zynq_interrupt_system_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_interrupt_system_axi_timer_0_0 || ORIG_REF_NAME==zynq_interrupt_system_axi_timer_0_0}]

# IP: bd/zynq_interrupt_system/ip/zynq_interrupt_system_xlconcat_0_0/zynq_interrupt_system_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_interrupt_system_xlconcat_0_0 || ORIG_REF_NAME==zynq_interrupt_system_xlconcat_0_0}]

# IP: bd/zynq_interrupt_system/ip/zynq_interrupt_system_auto_pc_0/zynq_interrupt_system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_interrupt_system_auto_pc_0 || ORIG_REF_NAME==zynq_interrupt_system_auto_pc_0}]

# XDC: bd/zynq_interrupt_system/ip/zynq_interrupt_system_processing_system7_0_0/zynq_interrupt_system_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynq_interrupt_system_processing_system7_0_0 || ORIG_REF_NAME==zynq_interrupt_system_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/zynq_interrupt_system/ip/zynq_interrupt_system_axi_gpio_0_0/zynq_interrupt_system_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynq_interrupt_system_axi_gpio_0_0 || ORIG_REF_NAME==zynq_interrupt_system_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/zynq_interrupt_system/ip/zynq_interrupt_system_axi_gpio_0_0/zynq_interrupt_system_axi_gpio_0_0_ooc.xdc

# XDC: bd/zynq_interrupt_system/ip/zynq_interrupt_system_axi_gpio_0_0/zynq_interrupt_system_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynq_interrupt_system_axi_gpio_0_0 || ORIG_REF_NAME==zynq_interrupt_system_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/zynq_interrupt_system/ip/zynq_interrupt_system_rst_processing_system7_0_50M_0/zynq_interrupt_system_rst_processing_system7_0_50M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_interrupt_system_rst_processing_system7_0_50M_0 || ORIG_REF_NAME==zynq_interrupt_system_rst_processing_system7_0_50M_0}]

# XDC: bd/zynq_interrupt_system/ip/zynq_interrupt_system_rst_processing_system7_0_50M_0/zynq_interrupt_system_rst_processing_system7_0_50M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_interrupt_system_rst_processing_system7_0_50M_0 || ORIG_REF_NAME==zynq_interrupt_system_rst_processing_system7_0_50M_0}]

# XDC: bd/zynq_interrupt_system/ip/zynq_interrupt_system_rst_processing_system7_0_50M_0/zynq_interrupt_system_rst_processing_system7_0_50M_0_ooc.xdc

# XDC: bd/zynq_interrupt_system/ip/zynq_interrupt_system_ZedboardOLED_0_0/src/charLib/charLib_ooc.xdc

# XDC: bd/zynq_interrupt_system/ip/zynq_interrupt_system_xbar_0/zynq_interrupt_system_xbar_0_ooc.xdc

# XDC: bd/zynq_interrupt_system/ip/zynq_interrupt_system_axi_timer_0_0/zynq_interrupt_system_axi_timer_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_interrupt_system_axi_timer_0_0 || ORIG_REF_NAME==zynq_interrupt_system_axi_timer_0_0}]

# XDC: bd/zynq_interrupt_system/ip/zynq_interrupt_system_axi_timer_0_0/zynq_interrupt_system_axi_timer_0_0_ooc.xdc

# XDC: bd/zynq_interrupt_system/ip/zynq_interrupt_system_auto_pc_0/zynq_interrupt_system_auto_pc_0_ooc.xdc

# XDC: bd/zynq_interrupt_system/zynq_interrupt_system_ooc.xdc
