# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /afs/ece.cmu.edu/usr/nryan/Private/545/GBA/vivado/GBA.srcs/sources_1/ip/palette_obj_ram/palette_obj_ram.xci
# IP: The module: 'palette_obj_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /afs/ece.cmu.edu/usr/nryan/Private/545/GBA/vivado/GBA.srcs/sources_1/ip/palette_obj_ram/palette_obj_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'palette_obj_ram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /afs/ece.cmu.edu/usr/nryan/Private/545/GBA/vivado/GBA.srcs/sources_1/ip/palette_obj_ram/palette_obj_ram.xci
# IP: The module: 'palette_obj_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /afs/ece.cmu.edu/usr/nryan/Private/545/GBA/vivado/GBA.srcs/sources_1/ip/palette_obj_ram/palette_obj_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'palette_obj_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
