# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /afs/ece.cmu.edu/usr/nryan/Desktop/mem_ctrl/mem_ctrl.cache/wt [current_project]
set_property parent.project_path /afs/ece.cmu.edu/usr/nryan/Desktop/mem_ctrl/mem_ctrl.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
add_files -quiet /afs/ece.cmu.edu/usr/nryan/Desktop/mem_ctrl/mem_ctrl.runs/InternRAM_synth_1/InternRAM.dcp
set_property used_in_implementation false [get_files /afs/ece.cmu.edu/usr/nryan/Desktop/mem_ctrl/mem_ctrl.runs/InternRAM_synth_1/InternRAM.dcp]
add_files -quiet /afs/ece.cmu.edu/usr/nryan/Desktop/mem_ctrl/mem_ctrl.runs/system_rom_synth_1/system_rom.dcp
set_property used_in_implementation false [get_files /afs/ece.cmu.edu/usr/nryan/Desktop/mem_ctrl/mem_ctrl.runs/system_rom_synth_1/system_rom.dcp]
add_files -quiet /afs/ece.cmu.edu/usr/nryan/Desktop/mem_ctrl/mem_ctrl.runs/vram_synth_1/vram.dcp
set_property used_in_implementation false [get_files /afs/ece.cmu.edu/usr/nryan/Desktop/mem_ctrl/mem_ctrl.runs/vram_synth_1/vram.dcp]
add_files -quiet /afs/ece.cmu.edu/usr/nryan/Desktop/mem_ctrl/mem_ctrl.runs/palette_ram_synth_1/palette_ram.dcp
set_property used_in_implementation false [get_files /afs/ece.cmu.edu/usr/nryan/Desktop/mem_ctrl/mem_ctrl.runs/palette_ram_synth_1/palette_ram.dcp]
add_files -quiet /afs/ece.cmu.edu/usr/nryan/Desktop/mem_ctrl/mem_ctrl.runs/OAM_synth_1/OAM.dcp
set_property used_in_implementation false [get_files /afs/ece.cmu.edu/usr/nryan/Desktop/mem_ctrl/mem_ctrl.runs/OAM_synth_1/OAM.dcp]
read_verilog /afs/ece.cmu.edu/usr/nryan/Private/545/GBA/mem/core_tb_defines.vh
read_verilog -library xil_defaultlib -sv {
  /afs/ece.cmu.edu/usr/nryan/Private/545/GBA/mem/mem_top.sv
  /afs/ece.cmu.edu/usr/nryan/Private/545/GBA/mem/mem_test.sv
}
read_xdc /afs/ece.cmu.edu/usr/nryan/Desktop/vivado_projects/board_test/zedboard_master_XDC_RevC_D_v3.xdc
set_property used_in_implementation false [get_files /afs/ece.cmu.edu/usr/nryan/Desktop/vivado_projects/board_test/zedboard_master_XDC_RevC_D_v3.xdc]

synth_design -top mem_test_CI -part xc7z020clg484-1
write_checkpoint -noxdef mem_test_CI.dcp
catch { report_utilization -file mem_test_CI_utilization_synth.rpt -pb mem_test_CI_utilization_synth.pb }
