# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /afs/ece.cmu.edu/usr/ryanovsk/Private/18545/GBA/dma/dma_test/dma_test.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.xci
# IP: The module: 'dist_mem_gen_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /afs/ece.cmu.edu/usr/ryanovsk/Private/18545/GBA/dma/dma_test/dma_test.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dist_mem_gen_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /afs/ece.cmu.edu/usr/ryanovsk/Private/18545/GBA/dma/dma_test/dma_test.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.xci
# IP: The module: 'dist_mem_gen_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /afs/ece.cmu.edu/usr/ryanovsk/Private/18545/GBA/dma/dma_test/dma_test.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dist_mem_gen_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
