# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /afs/ece.cmu.edu/usr/nryan/Desktop/mem_ctrl/mem_ctrl.srcs/sources_1/ip/system_rom/system_rom.xci
# IP: The module: 'system_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /afs/ece.cmu.edu/usr/nryan/Desktop/mem_ctrl/mem_ctrl.srcs/sources_1/ip/system_rom/system_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_rom'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /afs/ece.cmu.edu/usr/nryan/Desktop/mem_ctrl/mem_ctrl.srcs/sources_1/ip/system_rom/system_rom.xci
# IP: The module: 'system_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /afs/ece.cmu.edu/usr/nryan/Desktop/mem_ctrl/mem_ctrl.srcs/sources_1/ip/system_rom/system_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
