##################################################################################################
## 
##  Xilinx, Inc. 2010            www.xilinx.com 
##  Mon Oct 17 20:54:16 2016
##  Generated by MIG Version 2.3
##  
##################################################################################################
##  File name :       example_top.sdc
##  Details :     Constraints file
##                    FPGA Family:       ZYNQ
##                    FPGA Part:         XC7Z020ICLG484_PKG
##                    Speedgrade:        -1
##                    Design Entry:      VERILOG
##                    Frequency:         400 MHz
##                    Time Period:       2500 ps
##################################################################################################

##################################################################################################
## Controller 0
## Memory Device: DDR3_SDRAM->Components->MT41J128M8XX-125
## Data Width: 32
## Time Period: 2500
## Data Mask: 1
##################################################################################################

create_clock -period 10 [get_ports sys_clk_p]

create_clock -period 5 [get_ports clk_ref_p]

############## NET - IOSTANDARD ##################


