# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /afs/ece.cmu.edu/usr/nryan/Private/545/GBA/vivado/GBA.cache/wt [current_project]
set_property parent.project_path /afs/ece.cmu.edu/usr/nryan/Private/545/GBA/vivado/GBA.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
add_files -quiet /afs/ece.cmu.edu/usr/nryan/Private/545/GBA/vivado/GBA.runs/system_rom_synth_1/system_rom.dcp
set_property used_in_implementation false [get_files /afs/ece.cmu.edu/usr/nryan/Private/545/GBA/vivado/GBA.runs/system_rom_synth_1/system_rom.dcp]
add_files -quiet /afs/ece.cmu.edu/usr/nryan/Private/545/GBA/vivado/GBA.runs/InternRAM_synth_1/InternRAM.dcp
set_property used_in_implementation false [get_files /afs/ece.cmu.edu/usr/nryan/Private/545/GBA/vivado/GBA.runs/InternRAM_synth_1/InternRAM.dcp]
add_files -quiet /afs/ece.cmu.edu/usr/nryan/Private/545/GBA/vivado/GBA.runs/vram_A_synth_1/vram_A.dcp
set_property used_in_implementation false [get_files /afs/ece.cmu.edu/usr/nryan/Private/545/GBA/vivado/GBA.runs/vram_A_synth_1/vram_A.dcp]
add_files -quiet /afs/ece.cmu.edu/usr/nryan/Private/545/GBA/vivado/GBA.runs/vram_B_synth_1/vram_B.dcp
set_property used_in_implementation false [get_files /afs/ece.cmu.edu/usr/nryan/Private/545/GBA/vivado/GBA.runs/vram_B_synth_1/vram_B.dcp]
add_files -quiet /afs/ece.cmu.edu/usr/nryan/Private/545/GBA/vivado/GBA.runs/vram_C_synth_1/vram_C.dcp
set_property used_in_implementation false [get_files /afs/ece.cmu.edu/usr/nryan/Private/545/GBA/vivado/GBA.runs/vram_C_synth_1/vram_C.dcp]
add_files -quiet /afs/ece.cmu.edu/usr/nryan/Private/545/GBA/vivado/GBA.runs/palette_bg_ram_synth_1/palette_bg_ram.dcp
set_property used_in_implementation false [get_files /afs/ece.cmu.edu/usr/nryan/Private/545/GBA/vivado/GBA.runs/palette_bg_ram_synth_1/palette_bg_ram.dcp]
add_files -quiet /afs/ece.cmu.edu/usr/nryan/Private/545/GBA/vivado/GBA.runs/palette_obj_ram_synth_1/palette_obj_ram.dcp
set_property used_in_implementation false [get_files /afs/ece.cmu.edu/usr/nryan/Private/545/GBA/vivado/GBA.runs/palette_obj_ram_synth_1/palette_obj_ram.dcp]
add_files -quiet /afs/ece.cmu.edu/usr/nryan/Private/545/GBA/vivado/GBA.runs/OAM_synth_1/OAM.dcp
set_property used_in_implementation false [get_files /afs/ece.cmu.edu/usr/nryan/Private/545/GBA/vivado/GBA.runs/OAM_synth_1/OAM.dcp]
read_verilog /afs/ece.cmu.edu/usr/nryan/Private/545/GBA/gba_core_defines.vh
read_verilog -library xil_defaultlib -sv {
  /afs/ece.cmu.edu/usr/nryan/Private/545/GBA/mem/mem_top.sv
  /afs/ece.cmu.edu/usr/nryan/Private/545/GBA/controller/controller.sv
  /afs/ece.cmu.edu/usr/nryan/Private/545/GBA/gba_top.sv
}
read_xdc /afs/ece.cmu.edu/usr/nryan/Private/545/GBA/zedboard_master_XDC_RevC_D_v3.xdc
set_property used_in_implementation false [get_files /afs/ece.cmu.edu/usr/nryan/Private/545/GBA/zedboard_master_XDC_RevC_D_v3.xdc]

synth_design -top gba_top -part xc7z020clg484-1
write_checkpoint -noxdef gba_top.dcp
catch { report_utilization -file gba_top_utilization_synth.rpt -pb gba_top_utilization_synth.pb }
